name: dear_diary
description: Assignment 2 Part 1
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  intl: ^0.18.1
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  firebase_ui_auth: ^1.10.0
  firebase_storage: ^11.2.8
  cloud_firestore: ^4.13.1
  image_picker: ^1.0.4
  firebase_ui_oauth_google: ^1.2.14
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.0.4
  analyzer: 6.2.0

flutter:
  uses-material-design: true
