// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3MQfIDW4qPfoxKN88kN0kb-8oukDM9yc',
    appId: '1:964160602034:web:ced3101b5238cf09502eab',
    messagingSenderId: '964160602034',
    projectId: 'diary-app-1-1238c',
    authDomain: 'diary-app-1-1238c.firebaseapp.com',
    storageBucket: 'diary-app-1-1238c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4JSmDRnZa37_Z7gdq4aVNdfmXurezuhY',
    appId: '1:964160602034:android:e41c20456dfd0e2c502eab',
    messagingSenderId: '964160602034',
    projectId: 'diary-app-1-1238c',
    storageBucket: 'diary-app-1-1238c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDerN3xPPwUaB8_C0W1i06qZWYH5Ic1Cxc',
    appId: '1:964160602034:ios:5ad9c89bf720564b502eab',
    messagingSenderId: '964160602034',
    projectId: 'diary-app-1-1238c',
    storageBucket: 'diary-app-1-1238c.appspot.com',
    iosBundleId: 'com.example.dearDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDerN3xPPwUaB8_C0W1i06qZWYH5Ic1Cxc',
    appId: '1:964160602034:ios:9ab4761a6d441e8e502eab',
    messagingSenderId: '964160602034',
    projectId: 'diary-app-1-1238c',
    storageBucket: 'diary-app-1-1238c.appspot.com',
    iosBundleId: 'com.example.dearDiary.RunnerTests',
  );
}
